/* auto-generated by napi-rs */

/** Options for constructing a RenderEngine. */
export interface RenderEngineOptions {
  width: number
  height: number
  enableGpu: boolean
}

/** Step 2 / 3 / 4: Headless wgpu RenderEngine. */
export declare class RenderEngine {
  /** Create a new headless RenderEngine. */
  constructor(options: RenderEngineOptions)
  /** Returns the render target width. */
  get width(): number
  /** Returns the render target height. */
  get height(): number
  /**
   * Step 3: Add a primitive to the scene and return its unique numeric entity ID.
   * @param primitiveType - e.g. `"cube"`, `"sphere"`
   * @returns A unique `number` (u32) entity ID to pass to `setTransform`.
   */
  addPrimitive(primitiveType: string): number
  /**
   * Step 3: Update the world-space transform of an existing scene object.
   * @param id       - The numeric entity ID returned by `addPrimitive` or `loadModel`.
   * @param position - `[x, y, z]` translation.
   * @param rotation - `[x, y, z, w]` unit quaternion (Three.js Quaternion order).
   */
  setTransform(id: number, position: Array<number>, rotation: Array<number>): void
  /**
   * Step 5 / 6: Set the camera for the next `renderRaw` call.
   *
   * Uses a right-handed coordinate system (Three.js / OpenGL convention):
   * +X is right, +Y is up, +Z points toward the viewer.
   *
   * @param position   - `[x, y, z]` eye position in world space.
   * @param target     - `[x, y, z]` look-at point in world space.
   * @param fovDegrees - Vertical field-of-view in degrees.
   */
  setCamera(position: Array<number>, target: Array<number>, fovDegrees: number): void
  /**
   * Step 6: Add a directional light to the scene.
   *
   * @param direction - `[x, y, z]` direction the light travels (from source toward scene).
   *                    Matches Three.js `DirectionalLight` convention.
   * @param intensity - Light intensity scalar (recommended range 0.0 – 1.0).
   */
  addDirectionalLight(direction: Array<number>, intensity: number): void
  /**
   * Step 4: Render the current scene and return raw RGBA pixel data.
   * @param cameraId - Reserved for future use; pass any string (e.g. `"default"`).
   * @returns A `Uint8Array` of length `width * height * 4` in RGBA byte order.
   */
  renderRaw(cameraId: string): Uint8Array
  /**
   * Step 7: Load a GLTF/GLB model from the local file system and add it to the scene.
   * @param filePath - Absolute or relative path to a `.gltf` or `.glb` file.
   * @returns A unique `number` (u32) entity ID usable with `setTransform`.
   */
  loadModel(filePath: string): number
  /**
   * Step 8: Render the current scene and return the frame encoded as JPEG.
   * @param cameraId - Reserved for future use; pass any string (e.g. `"default"`).
   * @param quality  - JPEG quality in the range 1–100.
   * @returns A `Uint8Array` containing the JPEG byte stream (starts with `FF D8 FF`).
   */
  renderFrameJpeg(cameraId: string, quality: number): Uint8Array
  /**
   * Step 8: Render the current scene and return the raw depth buffer.
   * @param cameraId - Reserved for future use; pass any string (e.g. `"default"`).
   * @returns A `Float32Array` of length `width * height` with depth values in `[0.0, 1.0]`.
   */
  renderDepth(cameraId: string): Float32Array
}

/**
 * Step 1: A simple sum function to verify the napi-rs build pipeline works.
 */
export declare function sum(a: number, b: number): number
