/* auto-generated by napi-rs */

/** Options for constructing a RenderEngine. */
export interface RenderEngineOptions {
  width: number
  height: number
  enableGpu: boolean
}

/** Step 2: Headless wgpu RenderEngine. */
export declare class RenderEngine {
  /** Create a new headless RenderEngine. */
  constructor(options: RenderEngineOptions)
  /** Returns the render target width. */
  get width(): number
  /** Returns the render target height. */
  get height(): number
}

/**
 * Step 1: A simple sum function to verify the napi-rs build pipeline works.
 */
export declare function sum(a: number, b: number): number
